stages:
  - codequality
  - publish

phpqa:
  stage: codequality
  image: zdenekdrahos/phpqa:v1.18.0
  variables:
    BACKEND_QA: "*/backend/var/QA"
    BACKEND_CACHE: $CI_PROJECT_DIR/.composer
  cache:
    paths:
    - $BACKEND_CACHE
  script:
    - export COMPOSER_CACHE_DIR=$BACKEND_CACHE
    - mkdir phpqa
    - phpqa --report --tools phpmd:100,phpcpd:100,phploc,pdepend --buildDir ./phpqa
     - mv phpqa/ public/
  allow_failure: true
  artifacts:
    paths: 
    - public

pages:
  stage: publish
  image: alpine
  script:
  - apk update && apk add doxygen
  - doxygen .doxygen
  - mv Documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
