stages:
  - codequality
  - publish

codeclimate:
  stage: codequality
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - mkdir codeclimate
    - docker run --env SOURCE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" analyze -f html /code analyze -f html > codeclimate/codeclimate.html
    - 'ls -la codeclimate'
  artifacts:
    paths: 
    - codeclimate/

phpqa:
  stage: codequality
  image: zdenekdrahos/phpqa:v1.18.0
  allow_failure: true
  variables:
    BACKEND_QA: "*/backend/var/QA"
    BACKEND_CACHE: $CI_PROJECT_DIR/.composercache
  cache:
    paths:
    - $BACKEND_CACHE
  script:
    - 'export COMPOSER_CACHE_DIR=$BACKEND_CACHE'
    - 'composer install --ignore-platform-reqs --no-progress --no-suggest'
    - 'phpqa --report --tools phpcs:10000,phpunit:10000 --buildDir phpqa/ --analyzedDirs ./ --ignoredDirs var,vendor'
  artifacts:
    when: always
    paths:
    - phpqa/
    
pages:
  stage: publish
  image: alpine
  dependencies: 
    - phpqa
    - codeclimate
  script:
    - 'ls -la'
    - apk update && apk add doxygen
    - doxygen .doxygen
    - mkdir .public
    - mv phpqa/ .public/
    - 'ls -la codeclimate/'
    - mv codeclimate/ .public/
    - mv Documentation/doxygen/ .public/
    - 'ls -la .public/'
    - mv .public public
    - 'ls -la public/'
  artifacts:
    paths:
    - public
  only:
  - master
