stages:
  - codequality
  - publish

phpqa:
  stage: codequality
  image: zdenekdrahos/phpqa:v1.18.0
  allow_failure: true
  variables:
    BACKEND_QA: "*/backend/var/QA"
    BACKEND_CACHE: $CI_PROJECT_DIR/.composercache
  cache:
    paths:
    - $BACKEND_CACHE
  script:
    - 'export COMPOSER_CACHE_DIR=$BACKEND_CACHE'
    - 'composer install --ignore-platform-reqs --no-progress --no-suggest'
    - 'phpqa --report --tools phpcs:10000,phpunit:10000 --buildDir build/phpqa/ --analyzedDirs ./ --ignoredDirs var,vendor'
#    - mv build/phpqa/ public/
  artifacts:
    when: always
    paths:
    - phpqa
    
pages:
  stage: publish
  image: alpine
  dependencies: 
    - codequality
  script:
  - apk update && apk add doxygen
  - doxygen .doxygen
  - mv phpqa/ public/
  - mv Documentation/doxygen/ public/
  artifacts:
    paths:
    - public
  only:
  - master
