stages:
  - codequality
  - build
  - deploy

codeclimate:
  stage: codequality
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - docker run --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f html > codeclimate.html
  artifacts:
    paths:
    - codeclimate.html

build_phar:
  stage: build
  script:
    - composer install
  artifacts:
    expire_in: '1 hour'
    paths:
      - typo3reverse.phar

push_phar:
  image: inetprocess/gitlab-release
  stage: deploy
  dependencies:
    - build_phar
  only:
    - tag
  script:
    - gitlab-release --message 'New automated release' typo3reverse.phar

doxygen:
  stage: build
  image: alpine
  script:
    - apk update && apk add doxygen
    - doxygen .doxygen
  artifacts:
    paths:
    - Documentation/doxygen/

pages:
  stage: deploy
  image: alpine
  dependencies:
    - codeclimate
    - doxygen
  script:
    - echo 'Copy bits an pieces'
    - mkdir .public
    - wget -O .public/index.php https://gitlab.knallimall.org/snippets/32/raw
    - echo "<li>Commit $CI_COMMIT_SHA</li><li>Branch $CI_COMMIT_REF_NAME</li>" >> git.txt
    - mv git.txt .public/
    - mv codeclimate.html .public/
    - mv Documentation/doxygen/ .public/
    - mv .public public/
  artifacts:
    paths:
    - public/
  only:
  - master
