stages:
  - codequality
  - publish

codequality:
  stage: codequality
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    #- docker run --env SOURCE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock "hub.knallimall.org/docker/codequality:latest" /code
    - mkdir ./codeclimate
    - docker run --env SOURCE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" analyze -f html /code analyze -f html > codeclimate/codeclimate.html
    - mv codeclimate/ public/
  artifacts:
    paths: 
    - public

phpqa:
  stage: codequality
  image: zdenekdrahos/phpqa:v1.18.0
  variables:
    BACKEND_QA: "*/backend/var/QA"
    BACKEND_CACHE: $CI_PROJECT_DIR/.composer
  cache:
    paths:
    - $BACKEND_CACHE
  script:
    - export COMPOSER_CACHE_DIR=$BACKEND_CACHE
    - mkdir ./phpqa
    - phpqa --report --tools phpmd:100,phpcpd:100,phploc,pdepend --buildDir ./phpqa
    #--buildDir ./.Build/QA --analyzedDirs ./Classes --ignoredDirs ./Tests,./.Build
    - mv phpqa/ public/
  allow_failure: true
  artifacts:
    paths: 
    - public

pages:
  stage: publish
  image: alpine
  script:
  - apk update && apk add doxygen
  - doxygen .doxygen
  - mv Documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
